spring.application.name=medical_distributor
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/medicine_distribution
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update